Repository kubernetes-sigs/container-object-storage-interface-api, pull requests merged in 2020-12, with the labels that each got.

#6 Change to get kubeconfig from commandlin or env
  controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7 Adding new method to create controoler with clientset.
  controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8 Adding a object reference that can be used as a reference to BR, BAR …
  apis/objectstorage.k8s.io/v1alpha1/openapi_generated.go
  apis/objectstorage.k8s.io/v1alpha1/types.go
  apis/objectstorage.k8s.io/v1alpha1/zz_generated.deepcopy.go
  crds/objectstorage.k8s.io_bucketaccesses.yaml
  crds/objectstorage.k8s.io_buckets.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#10 Removing BucketClassListener and BucketAccessClassListener
  controller/controller.go
  controller/interfaces.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#11 updated README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#13 crds: add `kustomization.yaml`
  crds/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S
