Repository kubernetes-sigs/container-object-storage-interface-api, pull requests merged in 2021-03, with the labels that each got.

#23 adds conversion methods between spec and API
  .gitignore
  README.md
  apis/objectstorage.k8s.io/v1alpha1/azure_types.go
  apis/objectstorage.k8s.io/v1alpha1/gcs_types.go
  apis/objectstorage.k8s.io/v1alpha1/openapi_generated.go
  apis/objectstorage.k8s.io/v1alpha1/protocol_types.go
  apis/objectstorage.k8s.io/v1alpha1/s3_types.go
  clientset/fake/register.go
  crds/objectstorage.k8s.io_bucketaccessclasses.yaml
  crds/objectstorage.k8s.io_bucketaccesses.yaml
  crds/objectstorage.k8s.io_bucketaccessrequests.yaml
  crds/objectstorage.k8s.io_bucketclasses.yaml
  crds/objectstorage.k8s.io_bucketrequests.yaml
  crds/objectstorage.k8s.io_buckets.yaml
  docs/deployment-guide.md
  docs/index.md
  go.mod
  go.sum
  hack/update-codegen.sh
  kustomization.yaml
  listers/objectstorage.k8s.io/v1alpha1/bucket.go
  listers/objectstorage.k8s.io/v1alpha1/bucketaccess.go
  listers/objectstorage.k8s.io/v1alpha1/bucketaccessclass.go
  listers/objectstorage.k8s.io/v1alpha1/bucketaccessrequest.go
  listers/objectstorage.k8s.io/v1alpha1/bucketclass.go
  listers/objectstorage.k8s.io/v1alpha1/bucketrequest.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#25 Fix bucket* controller framework
  controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#26 Updated link to documentation
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#28 fix controller logic to prevent concurrent map reads and writes
  controller/controller.go
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#30 fixed the git repo name
  docs/deployment-guide.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#27 adds security policy, bug and enhancement templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/SECURITY.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#31 Update API based on latest spec
  apis/objectstorage.k8s.io/v1alpha1/openapi_generated.go
  apis/objectstorage.k8s.io/v1alpha1/protocol_types.go
  apis/objectstorage.k8s.io/v1alpha1/types.go
  apis/objectstorage.k8s.io/v1alpha1/zz_generated.deepcopy.go
  clientset/fake/register.go
  controller/controller.go
  crds/objectstorage.k8s.io_bucketaccessclasses.yaml
  crds/objectstorage.k8s.io_bucketaccesses.yaml
  crds/objectstorage.k8s.io_bucketaccessrequests.yaml
  crds/objectstorage.k8s.io_bucketclasses.yaml
  crds/objectstorage.k8s.io_bucketrequests.yaml
  crds/objectstorage.k8s.io_buckets.yaml
  listers/objectstorage.k8s.io/v1alpha1/bucket.go
  listers/objectstorage.k8s.io/v1alpha1/bucketaccess.go
  listers/objectstorage.k8s.io/v1alpha1/bucketaccessclass.go
  listers/objectstorage.k8s.io/v1alpha1/bucketaccessrequest.go
  listers/objectstorage.k8s.io/v1alpha1/bucketclass.go
  listers/objectstorage.k8s.io/v1alpha1/bucketrequest.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#34 remove provisioner from bucketAccess
  apis/objectstorage.k8s.io/v1alpha1/openapi_generated.go
  apis/objectstorage.k8s.io/v1alpha1/types.go
  crds/objectstorage.k8s.io_bucketaccesses.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#35 use bucketName instead of bucketName and bucketInstanceName
  apis/objectstorage.k8s.io/v1alpha1/azure_types.go
  apis/objectstorage.k8s.io/v1alpha1/gcs_types.go
  apis/objectstorage.k8s.io/v1alpha1/openapi_generated.go
  apis/objectstorage.k8s.io/v1alpha1/s3_types.go
  apis/objectstorage.k8s.io/v1alpha1/types.go
  controller/controller.go
  crds/objectstorage.k8s.io_bucketaccesses.yaml
  crds/objectstorage.k8s.io_bucketaccessrequests.yaml
  crds/objectstorage.k8s.io_bucketrequests.yaml
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M
