Repository kubernetes-sigs/container-object-storage-interface-api, pull requests merged in 2021-05, with the labels that each got.

#42 ensure that indexer has latest instance of an object
  controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#41 Removes bucketName fields from Protocol
  apis/objectstorage.k8s.io/v1alpha1/azure_types.go
  apis/objectstorage.k8s.io/v1alpha1/gcs_types.go
  apis/objectstorage.k8s.io/v1alpha1/openapi_generated.go
  apis/objectstorage.k8s.io/v1alpha1/protocol_types.go
  apis/objectstorage.k8s.io/v1alpha1/s3_types.go
  apis/objectstorage.k8s.io/v1alpha1/types.go
  crds/objectstorage.k8s.io_bucketclasses.yaml
  crds/objectstorage.k8s.io_buckets.yaml
  kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#46 updated links in README.md
  README.md
  docs/deployment-guide.md
  docs/index.md
  docs/meetings.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L
