Repository kubernetes-sigs/container-object-storage-interface-api, pull requests merged in 2022-08, with the labels that each got.

#56 Update the bucket info api and add namespace to BucketAccess client
  apis/bucket_info.go
  apis/objectstorage/v1alpha1/types.go
  client/clientset/versioned/typed/objectstorage/v1alpha1/bucketaccess.go
  client/clientset/versioned/typed/objectstorage/v1alpha1/fake/fake_bucketaccess.go
  client/clientset/versioned/typed/objectstorage/v1alpha1/fake/fake_objectstorage_client.go
  client/clientset/versioned/typed/objectstorage/v1alpha1/objectstorage_client.go
  client/informers/externalversions/objectstorage/v1alpha1/bucketaccess.go
  client/informers/externalversions/objectstorage/v1alpha1/interface.go
  client/listers/objectstorage/v1alpha1/bucketaccess.go
  client/listers/objectstorage/v1alpha1/expansion_generated.go
Labels: ok-to-test, cncf-cla: yes, approved, lgtm, size/L

#57 Fixing the pkg import in the BucketInfo api
  apis/bucket_info.go
Labels: ok-to-test, size/XS, cncf-cla: yes, approved, lgtm

#58 Fixing the import string
  apis/bucket_info.go
Labels: ok-to-test, size/XS, cncf-cla: yes, approved, lgtm

#59 Fix the annotation of the kustomization file
  kustomization.yaml
Labels: ok-to-test, size/XS, cncf-cla: yes, approved, lgtm

#60 Create CHANGELOG-0.1.md
  CHANGELOG/CHANGELOG-0.1.md
Labels: size/S, cncf-cla: yes, approved, lgtm
