Repository kubernetes-sigs/container-object-storage-interface-api, pull requests merged in 2024-08, with the labels that each got.

#85 Fix recording events
  controller/controller.go
Labels: size/XS, cncf-cla: yes, approved, lgtm

#89 monorepo: move event reason defs to api
  client/apis/objectstorage/v1alpha1/events.go
Labels: ok-to-test, size/XS, cncf-cla: yes, approved, lgtm

#90 monorepo: rename 'controller' dir to 'internal/runtime'
  internal/go.mod
  internal/go.sum
  internal/runtime/controller.go
  internal/runtime/interfaces.go
Labels: cncf-cla: yes, approved, lgtm, size/L

#91 monorepo: move imported controller to 'controller'
  controller/Dockerfile
  controller/Makefile
  controller/cloudbuild.yaml
  controller/cmd/controller-manager/controller-manager.go
  controller/go.mod
  controller/go.sum
  controller/kustomization.yaml
  controller/pkg/bucketclaim/bucketclaim.go
  controller/pkg/bucketclaim/bucketclaim_test.go
  controller/pkg/util/const.go
  controller/pkg/util/util.go
  controller/resources/deployment.yaml
  controller/resources/rbac.yaml
  controller/resources/sa.yaml
  internal/runtime/controller.go
Labels: cncf-cla: yes, approved, lgtm, size/L
